import pytest

from clone_repo import parse_repo_url
from clone_repo.parse_repo_url import RepoURL

EXAMPLES = (
    (
        "keybase://team/twomeylee/twomeylee.name",
        RepoURL(
            "keybase://team/twomeylee/twomeylee.name",
            "git",
            "keybase",
            "twomeylee",
            "twomeylee.name",
        ),
    ),
    (
        "git@github.com:micktwomey/elm-mdl-workshop.git",
        RepoURL(
            "git@github.com:micktwomey/elm-mdl-workshop.git",
            "git",
            "github.com",
            "micktwomey",
            "elm-mdl-workshop",
        ),
    ),
    (
        "https://github.com/micktwomey/elm-mdl-workshop.git",
        RepoURL(
            "https://github.com/micktwomey/elm-mdl-workshop.git",
            "git",
            "github.com",
            "micktwomey",
            "elm-mdl-workshop",
        ),
    ),
    (
        "git@gitlab.twomeylee.name:micktwomey/twomeylee-pi.git",
        RepoURL(
            "git@gitlab.twomeylee.name:micktwomey/twomeylee-pi.git",
            "git",
            "gitlab.twomeylee.name",
            "micktwomey",
            "twomeylee-pi",
        ),
    ),
    (
        "https://gitlab.twomeylee.name/micktwomey/twomeylee-pi.git",
        RepoURL(
            "https://gitlab.twomeylee.name/micktwomey/twomeylee-pi.git",
            "git",
            "gitlab.twomeylee.name",
            "micktwomey",
            "twomeylee-pi",
        ),
    ),
    (
        "ssh://hg@bitbucket.org/micktwomey/pyiso8601",
        RepoURL(
            "ssh://hg@bitbucket.org/micktwomey/pyiso8601",
            "hg",
            "bitbucket.org",
            "micktwomey",
            "pyiso8601",
        ),
    ),
    (
        "man@man.sr.ht:~micktwomey/Micki",
        RepoURL(
            "man@man.sr.ht:~micktwomey/Micki",
            "git",
            "man.sr.ht",
            "~micktwomey",
            "Micki",
        ),
    ),
    (
        "ssh://git@sourcecode.example.com:7999/somegroup/myrepo.git",
        RepoURL(
            "ssh://git@sourcecode.example.com:7999/somegroup/myrepo.git",
            "git",
            "sourcecode.example.com:7999",
            "somegroup",
            "myrepo",
        ),
    ),
    (
        "https://hg.sr.ht/~sircmpwn/invertbucket",
        RepoURL(
            "https://hg.sr.ht/~sircmpwn/invertbucket",
            "hg",
            "hg.sr.ht",
            "~sircmpwn",
            "invertbucket",
        ),
    ),
    (
        "https://hg.mozilla.org/mozilla-central/",
        RepoURL(
            "https://hg.mozilla.org/mozilla-central/",
            "hg",
            "hg.mozilla.org",
            "",
            "mozilla-central",
        ),
    ),
    (
        "git@github.com:micktwomey/micktwomey.github.io.git",
        RepoURL(
            "git@github.com:micktwomey/micktwomey.github.io.git",
            "git",
            "github.com",
            "micktwomey",
            "micktwomey.github.io",
        ),
    ),
    (
        "/path/to/repo",
        RepoURL(
            "/path/to/repo",
            "git",
            "localhost",
            "file",
            "repo",
        ),
    ),
    (
        "file:///path/to/repo",
        RepoURL(
            "file:///path/to/repo",
            "git",
            "localhost",
            "file",
            "repo",
        ),
    ),
    (
        "https://github.com/micktwomey/sync-camera-disk",
        RepoURL(
            "git@github.com:micktwomey/sync-camera-disk.git",
            "git",
            "github.com",
            "micktwomey",
            "sync-camera-disk",
        ),
    ),
)


@pytest.mark.parametrize("url,expected", EXAMPLES)
def test_parse_url(url: str, expected: RepoURL) -> None:
    assert parse_repo_url.parse_url(url) == expected
